version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
