version: '3.9'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
  app:
    build: .
    image: node-app
    container_name: node-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_DIALECT=mongodb
      - MONGO_URI=mongodb://mongo:27017/Test
      - JWT_SECRET=secret
    depends_on:
      mongo:
        condition: service_started
    networks:
      - app-network
networks:
  app-network:
    driver: bridge