services:
    postgres-local:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
    mongodb-local:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
        # Remove command and develop keys when using Docker Compose in production
        command: sh -c "yarn build && yarn lint && node --harmony dist/server.js"
        develop:
            watch:
                - action: sync+restart
                  path: ./src
                  target: /app/src
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json
        image: node-app
        container_name: node-app
        restart: unless-stopped
        ports:
            - '3000:3000'
              # Remove environment key when using .env file
              #    environment:
              #      - PORT=3000
              #      - DB_DIALECT=postgres
              #      - DB_HOST=postgres-local
              #      - DB_PORT=5432
            #      - DB_NAME=postgres
            #      - DB_USER=postgres
            #      - DB_PASS=password
            #      - JWT_SECRET=secret
        env_file:
            - .env
        depends_on:
            - postgres-local
volumes:
    postgres-data:
    mongodb-data:
