version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app
    container_name: node-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_DIALECT=postgres
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=password
      - MONGO_URI=mongodb://mongo:27017/Test
      - JWT_SECRET=secret
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
